/* declaration */
export type EventType = 
    | 'PlayerMessage'
    | 'PlayerTravelled'
    | 'PlayerTransform'
    | 'PlayerTeleported'
    | 'PlayerDied'
    | 'PlayerBounced'
    | 'EntitySpawned'
    | 'ItemUsed'
    | 'ItemInteracted'
    | 'ItemEquipped'
    | 'ItemAcquired'
    | 'ItemDropped'
    | 'ItemSmelted'
    | 'ItemCrafted'
    | 'ItemTraded'
    | 'BlockPlaced'
    | 'BlockBroken'
    | 'MobKilled'
    | 'MobInteracted'
    | 'TargetBlockHit'